---
- name: OCP | Update Excluders
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - atomic-openshift-excluder
    - atomic-openshift-docker-excluder
  register: excluder_pkg_update
 
- name: OCP | Excluders | Are enabled/excluded?
  command: "{{ item }} status" # returns status either 'exclude' or 'unexclude' and 0 or 1 respectively
  with_items:
    - atomic-openshift-excluder
    - atomic-openshift-docker-excluder
  changed_when: ocp_excluders_state_result.rc == 1
  failed_when: ocp_excluders_state_result.rc not in [0,1]
  register: ocp_excluders_state_result

- name: OCP | Excluders | Enable/Exclude
  shell: "{{ item.item }} exclude"
  when: item is changed or excluder_pkg_update is changed
  with_items: "{{ ocp_excluders_state_result.results }}"
